### ISSUE TITLE
No diff changes

### ISSUE THREAD

**Issue by webchi** [IvanShamatov/cinematronix#1]
.... promised [here ](https://mkdev.me/posts/rails-5-i-vue-js-kak-perestat-muchatsya-s-frontendom-i-nachat-zhit)

> Diff на Github — что добавилось по сравнению с приложением по-умолчанию созданного через rails new

**Comment by IvanShamatov** [comment]
Я просто перезаливал перед какой-то презентацией этот проект и diff потёр... Сейчас пожалуй весь код придется обновить, в связи с webpacker 3 и чуточку изменившимся стилем

**Comment by webchi** [comment]
Было бы здорово))

**Comment by webchi** [comment]
Может загрузить хотя бы тот что был. Чтобы исходный код был к статье и к видео на ютьюбе. А то новое перезаливать можно долго.

**Comment by IvanShamatov** [comment]
@webchi, https://github.com/IvanShamatov/cinematronix/pull/2/files повторил, начну дальше писать по этой теме
